all:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk

bos:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/bos_client.spec.js

media:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/media_client.spec.js

bcc:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/bcc_client.spec.js

bcs:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/bcs_client.spec.js

face:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/face_client.spec.js

ocr:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/ocr_client.spec.js

ses:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/ses_client.spec.js

qns:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/qns_client.spec.js

lss:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/lss_client.spec.js

mct:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/mct_client.spec.js

auth:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/auth.spec.js

crypto:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/crypto.spec.js

vod:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/vod_client.spec.js
