all:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk

bcc:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/bcc_client.spec.js

bcs:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/bcs_client.spec.js

face:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/face_client.spec.js

ocr:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/ocr_client.spec.js

ses:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/ses_client.spec.js

auth:
	DEBUG=* ../node_modules/.bin/jasmine-node --verbose --growl --captureExceptions sdk/auth.spec.js
